name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy-register:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image for register-microservice
      - name: Build and push Docker image for register-microservice
        run: |
          cd register-microservice  # Cambiar al directorio donde está el Dockerfile del servicio de registro
          docker build -t alexismendozaa/register-microservice .
          docker push alexismendozaa/register-microservice:latest

      # 5. Set up SSH key for deployment
      - name: Set up SSH key for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST_REGISTER }} >> ~/.ssh/known_hosts

      # 6. SSH to EC2 and deploy
      - name: SSH to EC2 and deploy
        run: |
          echo "Iniciando despliegue en EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_REGISTER }} << 'EOF'
            # Detén y elimina cualquier contenedor anterior
            docker stop register-microservice || true
            docker rm register-microservice || true

            # Pull del nuevo contenedor desde DockerHub
            docker pull alexismendozaa/register-microservice:latest

            # Ejecuta el contenedor (en el puerto 3001)
            docker run -d -p 3001:3001 --name register-microservice alexismendozaa/register-microservice:latest

            echo "Despliegue completo. El contenedor está en ejecución."
          EOF
